version: '3.8'

services:
  central-system:
    container_name: central-system
    build: target
    ports:
      - 8887:8887
    restart: on-failure
    depends_on:
      - postgres-db
    networks:
      - central-system-network

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ezs
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - central-system-network

networks:
  central-system-network:
    driver: bridge

volumes:
  db-data:
