version: '3.8'

services:
  demoapp:
    container_name: demoapp
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - demoapp-postgres-db
    networks:
      - demoapp-network

  demoapp-postgres-db:
    image: postgres:latest
    container_name: demoapp-postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demoapp
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - demoapp-network

networks:
  demoapp-network:
    driver: bridge

volumes:
  db-data:
